import { useMemo } from 'react';
import { buildAmortization, buildQuarterlySchedule, formatCurrency } from '../lib/finance';
import blueLogo from '../../image/blue.png';
import { buildFeasibilityData } from '../lib/feasibility';

export default function FullReport({ plan, finance, t, language, reportRef }) {
  const chart = useMemo(() => buildAmortization(finance), [finance]);
  const schedule = useMemo(() => buildQuarterlySchedule(finance), [finance]);
  const location = plan.input?.state ? `${plan.input.state}, ${plan.input.district}, ${plan.input.block}` : plan.payload?.location || '-';
  const category = plan.input?.category || plan.payload?.business_category || '-';
  const schemeName = finance.scheme === 'Micro Finance Scheme' ? t.microScheme : finance.scheme === 'Term Loan Scheme' ? t.termScheme : t.notEligible;
  const generatedDate = new Intl.DateTimeFormat(language === 'hi' ? 'hi-IN' : language === 'te' ? 'te-IN' : 'en-IN', { day: 'numeric', month: 'long', year: 'numeric' }).format(new Date());
  const feasibility = buildFeasibilityData({ t, category, location });

  return <div ref={reportRef} className="full-report" aria-hidden="true">
    <ReportPage className="report-cover"><img src={blueLogo} alt="ARTHNITI" /><p className="report-kicker">{t.resultsEyebrow}</p><h1>{t.reportTitle}</h1><p className="report-lede">{t.resultsSubtitle}</p><div className="report-meta"><ReportMeta label={t.category} value={category} /><ReportMeta label={t.location} value={location} /><ReportMeta label={t.generatedOn} value={generatedDate} /></div></ReportPage>
    <ReportPage><ReportHeading title={t.financialPlan} /><ReportHeading title={t.financialSummary} /><div className="report-summary">{[[t.marginCapital, formatCurrency(plan.input.margin)], [t.projectCost, formatCurrency(finance.projectCost)], [t.loanEligible, formatCurrency(finance.sanctionedLoan)], [t.monthlyEmi, finance.eligible ? formatCurrency(finance.emi) : '-']].map(([label, value]) => <ReportMetric key={label} label={label} value={value} />)}</div><ReportHeading title={t.recommendedScheme} /><div className="report-details">{[[t.scheme, schemeName], [t.interestRate, finance.eligible ? `${finance.interest}%` : '-'], [t.loanAmount, finance.eligible ? formatCurrency(finance.loanAmount) : '-'], [t.maximumLoan, finance.eligible ? formatCurrency(finance.maxLoan) : '-'], [t.tenure, finance.eligible ? `${finance.tenureYears} ${t.years}` : '-'], [t.moratorium, finance.eligible ? `${finance.moratoriumMonths} ${t.months}` : '-'], [t.eligibilityStatus, finance.eligible ? t.eligible : t.notEligible]].map(([label, value]) => <ReportMeta key={label} label={label} value={value} />)}</div>{finance.eligible ? <p className="report-note">{t.repaymentBegins}</p> : <p className="report-alert">{t.notEligibleReason}</p>}</ReportPage>
    <ReportPage><ReportHeading title={t.capitalStructure} /><div className="report-capital"><ReportMetric label={t.contribution} value={formatCurrency(plan.input.margin)} /><div><div className="report-capital-bar"><span /><b /></div><p>10% / 90%</p></div><ReportMetric label={finance.eligible ? t.financing : t.requestedFinancing} value={formatCurrency(finance.loanAmount)} /></div><ReportHeading title={t.repaymentProfile} /><div className="report-chart"><ReportChart data={chart} /></div>{!finance.eligible && <p className="report-alert">{t.amortizationUnavailable}</p>}</ReportPage>
    {finance.eligible && <>{Array.from({ length: Math.ceil(schedule.length / 12) }, (_, pageIndex) => <ReportPage key={`schedule-${pageIndex}`}><ReportHeading title={t.repaymentSchedule} /><table className="report-table"><thead><tr><th>{t.quarter}</th><th>{t.quarterlyPayment}</th><th>{t.principal}</th><th>{t.interest}</th><th>{t.balance}</th></tr></thead><tbody>{schedule.slice(pageIndex * 12, pageIndex * 12 + 12).map((row) => <tr key={row.quarter}><td>{t.quarterShort}{row.quarter}</td><td>{formatCurrency(row.emi)}</td><td>{formatCurrency(row.principal)}</td><td>{formatCurrency(row.interest)}</td><td>{formatCurrency(row.balance)}</td></tr>)}</tbody></table></ReportPage>)}</>}
    <ReportPage><ReportHeading title={t.feasibilityTab} /><ReportHeading title={t.marketReach} /><p className="report-copy"><b>{t.consumerBase}</b><br />{feasibility.market}</p><ReportList label={t.channels} items={feasibility.channels} /><ReportHeading title={t.swot} /><div className="report-swot">{[[t.strengths, feasibility.strengths], [t.weaknesses, feasibility.weaknesses], [t.opportunities, feasibility.opportunities], [t.threats, feasibility.threats]].map(([title, items]) => <div key={title}><h3>{title}</h3><ReportList items={items} /></div>)}</div></ReportPage>
    <ReportPage><ReportHeading title={t.localRisks} /><ReportList items={feasibility.risks} /><ReportHeading title={t.opportunity} /><p className="report-copy"><b>{t.unservedNiche}</b><br />{feasibility.niche}</p><ReportHeading title={t.competition} /><p className="report-copy"><b>{t.medium}</b><br />{feasibility.competition}</p><ReportHeading title={t.pricing} /><p className="report-copy"><b>{feasibility.pricingRange}</b><br />{feasibility.pricingReason}</p><ReportHeading title={t.viability} /><p className="report-score">{feasibility.score} <small>/ 100</small></p><p className="report-copy">{feasibility.viabilityReason}</p><ReportHeading title={t.recommendations} /><ol className="report-recommendations">{feasibility.recommendations.map((item, index) => <li key={item}><b>{String(index + 1).padStart(2, '0')}</b>{item}</li>)}</ol></ReportPage>
  </div>;
}

function ReportPage({ children, className = '' }) { return <section data-pdf-page className={`report-page ${className}`}>{children}</section>; }
function ReportHeading({ title }) { return <div className="report-heading"><h2>{title}</h2></div>; }
function ReportMeta({ label, value }) { return <div className="report-meta-item"><small>{label}</small><strong>{value}</strong></div>; }
function ReportMetric({ label, value }) { return <div className="report-metric"><small>{label}</small><strong>{value}</strong></div>; }
function ReportList({ label, items = [] }) { return <div className="report-list">{label && <h3>{label}</h3>}<ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></div>; }
function ReportChart({ data }) { if (!data.length) return null; const width = 690; const height = 220; const max = Math.max(...data.map((item) => Math.max(item.cumulativePrincipal, item.cumulativeInterest))); const points = (key) => data.map((item, index) => `${(index / Math.max(data.length - 1, 1)) * width},${height - (item[key] / max) * (height - 20)}`).join(' '); return <svg viewBox={`0 0 ${width} ${height}`} role="img"><line x1="0" y1={height - 1} x2={width} y2={height - 1} stroke="#cfd3dd" /><polyline points={points('cumulativePrincipal')} fill="none" stroke="#1a237e" strokeWidth="3" /><polyline points={points('cumulativeInterest')} fill="none" stroke="#ff9933" strokeWidth="3" /></svg>; }
