export const translations = {
  en: {
    language: 'हिंदी', brandLine: 'FINANCE FOR LOCAL BUSINESS',
    eyebrow: 'A simpler path to working capital', title: 'Build what comes next.',
    subtitle: 'Access clear, practical finance for your local business.',
    identifier: 'Email or mobile number', identifierHint: 'Use the details linked to your application',
    password: 'Password', passwordHint: 'Enter your secure password', show: 'Show', hide: 'Hide',
    signIn: 'Sign in', signingIn: 'Signing in...', welcome: 'Welcome back',
    error: 'We could not sign you in. Check your details and try again.',
    demoHint: 'Your account is protected with secure sign-in.', footer: 'A trusted foundation for local enterprise.',
    placeholderIdentifier: 'you@example.com', placeholderPassword: 'Enter password',
    newToArthniti: 'New to Arthniti?', createAccount: 'Create an account', signupLanguage: 'हिंदी', signupEyebrow: 'ARTHNITI / CREATE ACCOUNT', signupTitle: 'Make room for what comes next.', signupSubtitle: 'Create your secure account first. We’ll ask about your business in the next step.', fullName: 'Full name', fullNamePlaceholder: 'Enter your full name', mobile: 'Mobile number', mobilePlaceholder: '10-digit mobile number', email: 'Email address', emailPlaceholder: 'you@example.com', createPassword: 'Password', createPasswordPlaceholder: 'At least 8 characters', confirmPassword: 'Confirm password', confirmPasswordPlaceholder: 'Re-enter your password', passwordHintSignup: 'Use at least 8 characters with one number.', createAccountButton: 'Create account', creatingAccount: 'Creating account...', alreadyHaveAccount: 'Already have an account?', signupSignIn: 'Sign in', signupRequired: 'Please complete this field.', invalidMobile: 'Enter a valid 10-digit mobile number.', invalidEmail: 'Enter a valid email address.', weakPassword: 'Use at least 8 characters with one number.', passwordMismatch: 'Passwords do not match.', signupError: 'We could not create your account right now. Please try again.', accountExists: 'An account with these details already exists.', signupPrivacy: 'Your account is private and protected.',
    startLanguage: 'हिंदी', startEyebrow: 'ARTHNITI / START', startTitle: 'Let’s understand your business.',
    startSubtitle: 'Tell us a little about where you work and what you want to build. We’ll use this to prepare a practical finance plan.',
    step: 'STEP', location: 'Your location', locationHelp: 'This helps us understand your local market and available schemes.',
    state: 'State', district: 'District', block: 'Block / Village', chooseState: 'Select state', chooseDistrict: 'Select district', chooseBlock: 'Select block or village',
    business: 'Your business', businessHelp: 'Choose the category that best describes your planned business.', category: 'Business category', chooseCategory: 'Select a category',
    capital: 'Your contribution', capitalHelp: 'This is your own money. It becomes your 10% contribution toward the project.', margin: 'Available margin capital', amountPlaceholder: 'Enter amount in rupees',
    continue: 'Generate my plan', generating: 'Preparing your plan...', required: 'Please complete this field.', invalidAmount: 'Enter an amount greater than ₹0.', submitError: 'We could not prepare your plan right now. Please try again.', rupees: '₹', secureNote: 'Your information is used only to prepare your plan.',
  },
  hi: {
    newToArthniti: 'अर्थनीति पर नए हैं?', createAccount: 'खाता बनाएं', signupLanguage: 'English', signupEyebrow: 'अर्थनीति / खाता बनाएं', signupTitle: 'अगले कदम के लिए जगह बनाएं।', signupSubtitle: 'पहले अपना सुरक्षित खाता बनाएं। अगले चरण में हम आपके व्यवसाय के बारे में पूछेंगे।', fullName: 'पूरा नाम', fullNamePlaceholder: 'अपना पूरा नाम दर्ज करें', mobile: 'मोबाइल नंबर', mobilePlaceholder: '10 अंकों का मोबाइल नंबर', email: 'ईमेल पता', emailPlaceholder: 'you@example.com', createPassword: 'पासवर्ड', createPasswordPlaceholder: 'कम से कम 8 अक्षर', confirmPassword: 'पासवर्ड की पुष्टि', confirmPasswordPlaceholder: 'पासवर्ड फिर दर्ज करें', passwordHintSignup: 'कम से कम 8 अक्षर और एक अंक का उपयोग करें।', createAccountButton: 'खाता बनाएं', creatingAccount: 'खाता बन रहा है...', alreadyHaveAccount: 'क्या आपका पहले से खाता है?', signupSignIn: 'साइन इन', signupRequired: 'कृपया यह जानकारी पूरी करें।', invalidMobile: 'मान्य 10-अंकों का मोबाइल नंबर दर्ज करें।', invalidEmail: 'मान्य ईमेल दर्ज करें।', weakPassword: 'कम से कम 8 अक्षर और एक अंक का उपयोग करें।', passwordMismatch: 'दोनों पासवर्ड अलग हैं।', signupError: 'अभी खाता नहीं बन सका। कृपया फिर कोशिश करें।', accountExists: 'इन विवरणों के साथ खाता पहले से मौजूद है।', signupPrivacy: 'आपका खाता निजी और सुरक्षित है।',
    language: 'English', brandLine: 'स्थानीय व्यवसाय के लिए वित्त',
    eyebrow: 'कार्यशील पूंजी का सरल रास्ता', title: 'अगला कदम बनाइए।',
    subtitle: 'अपने स्थानीय व्यवसाय के लिए स्पष्ट और व्यावहारिक वित्त पाएं।',
    identifier: 'ईमेल या मोबाइल नंबर', identifierHint: 'अपने आवेदन से जुड़ी जानकारी का उपयोग करें',
    password: 'पासवर्ड', passwordHint: 'अपना सुरक्षित पासवर्ड दर्ज करें', show: 'दिखाएं', hide: 'छिपाएं',
    signIn: 'साइन इन', signingIn: 'साइन इन हो रहा है...', welcome: 'वापसी पर स्वागत है',
    error: 'हम आपको साइन इन नहीं कर सके। अपनी जानकारी जांचकर फिर कोशिश करें।',
    demoHint: 'आपका खाता सुरक्षित साइन-इन से सुरक्षित है।', footer: 'स्थानीय उद्यम के लिए एक भरोसेमंद आधार।',
    placeholderIdentifier: 'you@example.com', placeholderPassword: 'पासवर्ड दर्ज करें',
    startLanguage: 'English', startEyebrow: 'अर्थनीति / शुरुआत', startTitle: 'अपने व्यवसाय को समझने से शुरू करें।',
    startSubtitle: 'हमें बताएं कि आप कहां काम करते हैं और क्या बनाना चाहते हैं। हम आपके लिए एक व्यावहारिक वित्त योजना तैयार करेंगे।',
    step: 'चरण', location: 'आपका स्थान', locationHelp: 'इससे हमें आपके स्थानीय बाजार और उपलब्ध योजनाओं को समझने में मदद मिलेगी।',
    state: 'राज्य', district: 'जिला', block: 'ब्लॉक / गांव', chooseState: 'राज्य चुनें', chooseDistrict: 'जिला चुनें', chooseBlock: 'ब्लॉक या गांव चुनें',
    business: 'आपका व्यवसाय', businessHelp: 'अपने प्रस्तावित व्यवसाय का सबसे उपयुक्त वर्ग चुनें।', category: 'व्यवसाय का वर्ग', chooseCategory: 'वर्ग चुनें',
    capital: 'आपका योगदान', capitalHelp: 'यह आपकी अपनी राशि है। यह परियोजना में आपके 10% योगदान के रूप में शामिल होगी।', margin: 'उपलब्ध मार्जिन पूंजी', amountPlaceholder: 'रुपये में राशि दर्ज करें',
    continue: 'मेरी योजना बनाएं', generating: 'आपकी योजना तैयार हो रही है...', required: 'कृपया यह जानकारी पूरी करें।', invalidAmount: '₹0 से अधिक राशि दर्ज करें।', submitError: 'अभी आपकी योजना तैयार नहीं हो सकी। कृपया फिर कोशिश करें।', rupees: '₹', secureNote: 'आपकी जानकारी का उपयोग केवल योजना तैयार करने के लिए किया जाता है।',
  },
};

export const LANGUAGE_STORAGE_KEY = 'arthniti_language';
export const SUPPORTED_LANGUAGES = ['en', 'hi', 'te'];

export function getInitialLanguage() {
  try {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    return SUPPORTED_LANGUAGES.includes(stored) ? stored : 'en';
  } catch { return 'en'; }
}

export function getNextLanguage(language) {
  return SUPPORTED_LANGUAGES[(SUPPORTED_LANGUAGES.indexOf(language) + 1) % SUPPORTED_LANGUAGES.length];
}

export function persistLanguage(language) {
  try { localStorage.setItem(LANGUAGE_STORAGE_KEY, language); } catch { /* Storage may be unavailable. */ }
}

Object.assign(translations.en, { changeLanguage: 'Change language', loginHeading: 'Sign in to continue', brandFooter: 'INDIA / LOCAL / GROWTH', startFinance: 'FINANCE FOR LOCAL BUSINESS', startHeading: 'Start with the essentials.', signupHeading: 'Create your account.', signupFooter: 'ACCOUNT / TRUST / GROWTH', copyright: '© 2026 ARTHNITI' });
Object.assign(translations.hi, { language: 'తెలుగు', startLanguage: 'తెలుగు', signupLanguage: 'తెలుగు', changeLanguage: 'भाषा बदलें', loginHeading: 'जारी रखने के लिए साइन इन करें', brandFooter: 'भारत / स्थानीय / विकास', startFinance: 'स्थानीय व्यवसाय के लिए वित्त', startHeading: 'ज़रूरी जानकारी से शुरुआत करें।', signupHeading: 'अपना खाता बनाएं।', signupFooter: 'खाता / भरोसा / विकास', copyright: '© 2026 ARTHNITI' });
Object.assign(translations.en, { resultsLanguage: 'हिंदी', resultsEyebrow: 'ARTHNITI / ASSESSMENT', resultsTitle: 'Your financial plan.', resultsSubtitle: 'A clear view of the capital structure for your business.', financialPlan: 'Financial plan', feasibilityComing: 'Feasibility report coming next', marginCapital: 'Margin capital', projectCost: 'Project cost', loanEligible: 'Loan eligible', monthlyEmi: 'Monthly EMI', recommendedScheme: 'Recommended scheme', scheme: 'Scheme', eligible: 'Eligible', microScheme: 'Micro Finance Scheme', termScheme: 'Term Loan Scheme', interestRate: 'Interest rate', loanAmount: 'Loan amount', maximumLoan: 'Maximum eligible loan', tenure: 'Tenure', moratorium: 'Moratorium', years: 'years', months: 'months', repaymentBegins: 'Repayment begins after the moratorium period.', principal: 'Principal', interest: 'Interest', repaymentSchedule: 'Quarterly repayment schedule', quarter: 'Quarter', quarterlyPayment: 'Quarterly payment', balance: 'Remaining balance', noResults: 'No financial plan found.', noResultsHelp: 'Complete your business details to generate a financial plan.', goToStart: 'Go to onboarding', loadingResults: 'Preparing your financial plan...', invalidResults: 'The saved plan is incomplete or invalid.', calculationError: 'We could not calculate this plan. Please try again.', notEligible: 'Not eligible', notEligibleReason: 'Project cost exceeds ₹50 lakh limit.', planContext: 'Based on your selected business and location.', category: 'Category', location: 'Location', noRepayment: 'No repayment schedule is available for this application.' });
Object.assign(translations.hi, { resultsLanguage: 'తెలుగు', resultsEyebrow: 'अर्थनीति / आकलन', resultsTitle: 'आपकी वित्तीय योजना।', resultsSubtitle: 'आपके व्यवसाय की पूंजी संरचना का स्पष्ट विवरण।', financialPlan: 'वित्तीय योजना', feasibilityComing: 'व्यवहार्यता रिपोर्ट जल्द आएगी', marginCapital: 'मार्जिन पूंजी', projectCost: 'परियोजना लागत', loanEligible: 'पात्र ऋण', monthlyEmi: 'मासिक ईएमआई', recommendedScheme: 'अनुशंसित योजना', scheme: 'योजना', eligible: 'पात्र', microScheme: 'सूक्ष्म वित्त योजना', termScheme: 'टर्म लोन योजना', interestRate: 'ब्याज दर', loanAmount: 'ऋण राशि', maximumLoan: 'अधिकतम पात्र ऋण', tenure: 'अवधि', moratorium: 'मोहलत', years: 'वर्ष', months: 'महीने', repaymentBegins: 'मोहलत अवधि के बाद भुगतान शुरू होगा।', principal: 'मूलधन', interest: 'ब्याज', repaymentSchedule: 'त्रैमासिक भुगतान अनुसूची', quarter: 'तिमाही', quarterlyPayment: 'त्रैमासिक भुगतान', balance: 'शेष राशि', noResults: 'कोई वित्तीय योजना नहीं मिली।', noResultsHelp: 'वित्तीय योजना बनाने के लिए अपने व्यवसाय का विवरण पूरा करें।', goToStart: 'ऑनबोर्डिंग पर जाएं', loadingResults: 'आपकी वित्तीय योजना तैयार हो रही है...', invalidResults: 'सहेजी गई योजना अधूरी या अमान्य है।', calculationError: 'हम इस योजना की गणना नहीं कर सके। कृपया फिर कोशिश करें।', notEligible: 'पात्र नहीं', notEligibleReason: 'परियोजना लागत ₹50 लाख से अधिक है।', planContext: 'आपके चुने हुए व्यवसाय और स्थान के आधार पर।', category: 'वर्ग', location: 'स्थान', noRepayment: 'इस आवेदन के लिए भुगतान अनुसूची उपलब्ध नहीं है।' });

translations.te = {
  language: 'హిందీ', brandLine: 'స్థానిక వ్యాపారం కోసం ఆర్థిక సహాయం', eyebrow: 'వర్కింగ్ క్యాపిటల్‌కు సులభమైన మార్గం', title: 'తర్వాతి అడుగు వేయండి.', subtitle: 'మీ స్థానిక వ్యాపారం కోసం స్పష్టమైన, ఆచరణాత్మక ఆర్థిక సహాయాన్ని పొందండి.', identifier: 'ఈమెయిల్ లేదా మొబైల్ నంబర్', identifierHint: 'మీ దరఖాస్తుకు అనుసంధానమైన వివరాలను ఉపయోగించండి', password: 'పాస్‌వర్డ్', passwordHint: 'మీ సురక్షిత పాస్‌వర్డ్‌ను నమోదు చేయండి', show: 'చూపించు', hide: 'దాచు', signIn: 'సైన్ ఇన్', signingIn: 'సైన్ ఇన్ అవుతోంది...', welcome: 'తిరిగి స్వాగతం', error: 'సైన్ ఇన్ చేయలేకపోయాం. మీ వివరాలను తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.', demoHint: 'మీ ఖాతా సురక్షిత సైన్-ఇన్‌తో రక్షించబడింది.', footer: 'స్థానిక వ్యాపారానికి నమ్మకమైన పునాది.', placeholderIdentifier: 'you@example.com', placeholderPassword: 'పాస్‌వర్డ్ నమోదు చేయండి',
  newToArthniti: 'అర్థనీతికి కొత్తవారా?', createAccount: 'ఖాతా సృష్టించండి', signupLanguage: 'హిందీ', signupEyebrow: 'ARTHNITI / ఖాతా సృష్టించండి', signupTitle: 'తర్వాతి అడుగుకు సిద్ధం అవ్వండి.', signupSubtitle: 'ముందుగా మీ సురక్షిత ఖాతాను సృష్టించండి. తదుపరి దశలో మీ వ్యాపారం గురించి అడుగుతాము.', fullName: 'పూర్తి పేరు', fullNamePlaceholder: 'మీ పూర్తి పేరు నమోదు చేయండి', mobile: 'మొబైల్ నంబర్', mobilePlaceholder: '10 అంకెల మొబైల్ నంబర్', email: 'ఈమెయిల్ చిరునామా', emailPlaceholder: 'you@example.com', createPassword: 'పాస్‌వర్డ్', createPasswordPlaceholder: 'కనీసం 8 అక్షరాలు', confirmPassword: 'పాస్‌వర్డ్ నిర్ధారణ', confirmPasswordPlaceholder: 'మీ పాస్‌వర్డ్‌ను మళ్లీ నమోదు చేయండి', passwordHintSignup: 'కనీసం 8 అక్షరాలు, ఒక సంఖ్యను ఉపయోగించండి.', createAccountButton: 'ఖాతా సృష్టించండి', creatingAccount: 'ఖాతా సృష్టించబడుతోంది...', alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?', signupSignIn: 'సైన్ ఇన్', signupRequired: 'దయచేసి ఈ వివరాన్ని పూర్తి చేయండి.', invalidMobile: 'చెల్లుబాటు అయ్యే 10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి.', invalidEmail: 'చెల్లుబాటు అయ్యే ఈమెయిల్ నమోదు చేయండి.', weakPassword: 'కనీసం 8 అక్షరాలు, ఒక సంఖ్యను ఉపయోగించండి.', passwordMismatch: 'రెండు పాస్‌వర్డ్‌లు సరిపోలడం లేదు.', signupError: 'ఇప్పుడు ఖాతా సృష్టించలేకపోయాం. దయచేసి మళ్లీ ప్రయత్నించండి.', accountExists: 'ఈ వివరాలతో ఖాతా ఇప్పటికే ఉంది.', signupPrivacy: 'మీ ఖాతా ప్రైవేట్‌గా మరియు సురక్షితంగా ఉంటుంది.',
  startLanguage: 'హిందీ', startEyebrow: 'ARTHNITI / ప్రారంభం', startTitle: 'మీ వ్యాపారాన్ని అర్థం చేసుకోవడంతో మొదలుపెడదాం.', startSubtitle: 'మీరు ఎక్కడ పని చేస్తున్నారు, ఏమి నిర్మించాలనుకుంటున్నారు అనే విషయాలను మాకు చెప్పండి. మీ కోసం ఆచరణాత్మక ఆర్థిక ప్రణాళికను సిద్ధం చేస్తాము.', step: 'దశ', location: 'మీ స్థానం', locationHelp: 'మీ స్థానిక మార్కెట్ మరియు అందుబాటులో ఉన్న పథకాలను అర్థం చేసుకోవడానికి ఇది సహాయపడుతుంది.', state: 'రాష్ట్రం', district: 'జిల్లా', block: 'బ్లాక్ / గ్రామం', chooseState: 'రాష్ట్రాన్ని ఎంచుకోండి', chooseDistrict: 'జిల్లాను ఎంచుకోండి', chooseBlock: 'బ్లాక్ లేదా గ్రామాన్ని ఎంచుకోండి', business: 'మీ వ్యాపారం', businessHelp: 'మీరు ప్రారంభించాలనుకుంటున్న వ్యాపారానికి సరైన వర్గాన్ని ఎంచుకోండి.', category: 'వ్యాపార వర్గం', chooseCategory: 'వర్గాన్ని ఎంచుకోండి', capital: 'మీ సహకారం', capitalHelp: 'ఇది మీ స్వంత డబ్బు. ప్రాజెక్టులో మీ 10% సహకారంగా ఇది పరిగణించబడుతుంది.', margin: 'అందుబాటులో ఉన్న మార్జిన్ మూలధనం', amountPlaceholder: 'రూపాయల్లో మొత్తాన్ని నమోదు చేయండి', continue: 'నా ప్రణాళికను రూపొందించండి', generating: 'మీ ప్రణాళిక సిద్ధమవుతోంది...', required: 'దయచేసి ఈ వివరాన్ని పూర్తి చేయండి.', invalidAmount: '₹0 కంటే ఎక్కువ మొత్తాన్ని నమోదు చేయండి.', submitError: 'ఇప్పుడు మీ ప్రణాళికను సిద్ధం చేయలేకపోయాం. దయచేసి మళ్లీ ప్రయత్నించండి.', rupees: '₹', secureNote: 'మీ సమాచారాన్ని ప్రణాళిక సిద్ధం చేయడానికి మాత్రమే ఉపయోగిస్తాము.',
  changeLanguage: 'భాష మార్చండి', loginHeading: 'కొనసాగించడానికి సైన్ ఇన్ చేయండి', brandFooter: 'భారతదేశం / స్థానికం / అభివృద్ధి', startFinance: 'స్థానిక వ్యాపారం కోసం ఆర్థిక సహాయం', startHeading: 'అవసరమైన వివరాలతో ప్రారంభించండి.', signupHeading: 'మీ ఖాతాను సృష్టించండి.', signupFooter: 'ఖాతా / నమ్మకం / అభివృద్ధి', copyright: '© 2026 ARTHNITI',
  resultsLanguage: 'English', resultsEyebrow: 'ARTHNITI / అంచనా', resultsTitle: 'మీ ఆర్థిక ప్రణాళిక.', resultsSubtitle: 'మీ వ్యాపార మూలధన నిర్మాణం యొక్క స్పష్టమైన వివరాలు.', financialPlan: 'ఆర్థిక ప్రణాళిక', feasibilityComing: 'సాధ్యత నివేదిక త్వరలో', marginCapital: 'మార్జిన్ మూలధనం', projectCost: 'ప్రాజెక్టు ఖర్చు', loanEligible: 'అర్హత ఉన్న రుణం', monthlyEmi: 'నెలవారీ EMI', recommendedScheme: 'సిఫార్సు చేసిన పథకం', interestRate: 'వడ్డీ రేటు', loanAmount: 'రుణ మొత్తం', maximumLoan: 'గరిష్ఠ అర్హత రుణం', tenure: 'కాలవ్యవధి', moratorium: 'మొరటోరియం', years: 'సంవత్సరాలు', months: 'నెలలు', repaymentBegins: 'మొరటోరియం కాలం తర్వాత చెల్లింపులు ప్రారంభమవుతాయి.', principal: 'అసలు', interest: 'వడ్డీ', repaymentSchedule: 'త్రైమాసిక చెల్లింపు షెడ్యూల్', quarter: 'త్రైమాసికం', quarterlyPayment: 'త్రైమాసిక చెల్లింపు', balance: 'మిగిలిన బాకీ', noResults: 'ఆర్థిక ప్రణాళిక కనుగొనబడలేదు.', noResultsHelp: 'ఆర్థిక ప్రణాళికను రూపొందించడానికి మీ వ్యాపార వివరాలను పూర్తి చేయండి.', goToStart: 'ఆన్‌బోర్డింగ్‌కు వెళ్లండి', loadingResults: 'మీ ఆర్థిక ప్రణాళిక సిద్ధమవుతోంది...', invalidResults: 'సేవ్ చేసిన ప్రణాళిక అసంపూర్ణంగా లేదా చెల్లనిదిగా ఉంది.', calculationError: 'ఈ ప్రణాళికను లెక్కించలేకపోయాం. దయచేసి మళ్లీ ప్రయత్నించండి.', notEligible: 'అర్హత లేదు', notEligibleReason: 'ప్రాజెక్టు ఖర్చు ₹50 లక్షలకు మించిపోయింది.', planContext: 'మీరు ఎంచుకున్న వ్యాపారం మరియు స్థానం ఆధారంగా.', category: 'వర్గం', location: 'స్థానం', mobileSchedule: 'త్రైమాసికం', monthRange: 'నెలలు', noRepayment: 'ఈ దరఖాస్తుకు చెల్లింపు షెడ్యూల్ అందుబాటులో లేదు.',
};
Object.assign(translations.te, { scheme: 'పథకం', eligible: 'అర్హత ఉంది', microScheme: 'సూక్ష్మ ఆర్థిక పథకం', termScheme: 'టర్మ్ లోన్ పథకం' });
Object.assign(translations.en, { capitalPosition: 'Capital position', contribution: 'Your contribution', financing: 'Financing', financialShare: 'Your 10% contribution and 90% financing structure.', repaymentProfile: 'Repayment profile', amortizationUnavailable: 'Amortization schedule unavailable because this application is not eligible.', feasibilityTab: 'Feasibility report', marketReach: 'Market reach', consumerBase: 'Consumer base', channels: 'Distribution channels', swot: 'SWOT', strengths: 'Strengths', weaknesses: 'Weaknesses', opportunities: 'Opportunities', threats: 'Threats', localRisks: 'Local risks', opportunity: 'Opportunity', unservedNiche: 'Unserved niche', competition: 'Competition', competitorDensity: 'Competitor density', reasoning: 'Reasoning', pricing: 'Pricing strategy', recommendedRange: 'Recommended range', viability: 'Viability', viabilityScore: 'Viability score', recommendations: 'Top 3 recommendations', recommendation: 'Recommendation', medium: 'Medium', mockConsumerBase: '~8,000 households within 10km of Nizamabad Rural', mockChannels: ['Local weekly market (santha)', 'Direct home delivery', 'Tie-up with 3 kirana stores'], mockStrengths: ['Strong local dairy demand', 'Low starting capital needed'], mockWeaknesses: ['No cold-chain access', 'First-time operator'], mockOpportunities: ['No organic milk supplier in block', 'Growing town population nearby'], mockThreats: ['Summer feed cost spikes', 'Dependence on single milk buyer'], mockRisks: ['Fodder price rises May-June', 'Monsoon transport disruption'], mockNiche: 'Packaged curd & buttermilk for the local town market', mockCompetitionReason: '6-8 informal dairy sellers, none branded', mockPricingRange: '₹48-55 per litre', mockPricingReason: 'Slightly above loose milk, justified by hygiene & delivery', mockViabilityReason: 'Solid demand, manageable risks, clear pricing edge', mockRecommendations: ['Start with 4-5 buffaloes to prove demand before scaling', 'Lock a fodder supplier before summer', 'Brand as hygienic/home-delivered to command premium'] });
Object.assign(translations.hi, { capitalPosition: 'पूंजी स्थिति', contribution: 'आपका योगदान', financing: 'वित्तपोषण', financialShare: 'आपका 10% योगदान और 90% वित्तपोषण ढांचा।', repaymentProfile: 'भुगतान प्रोफ़ाइल', amortizationUnavailable: 'यह आवेदन पात्र नहीं है, इसलिए परिशोधन अनुसूची उपलब्ध नहीं है।', feasibilityTab: 'व्यवहार्यता रिपोर्ट', marketReach: 'बाजार पहुंच', consumerBase: 'उपभोक्ता आधार', channels: 'वितरण चैनल', swot: 'SWOT', strengths: 'ताकत', weaknesses: 'कमजोरियां', opportunities: 'अवसर', threats: 'खतरे', localRisks: 'स्थानीय जोखिम', opportunity: 'अवसर', unservedNiche: 'अपूर्ति वाला क्षेत्र', competition: 'प्रतिस्पर्धा', competitorDensity: 'प्रतिस्पर्धी घनत्व', reasoning: 'कारण', pricing: 'मूल्य निर्धारण रणनीति', recommendedRange: 'अनुशंसित सीमा', viability: 'व्यवहार्यता', viabilityScore: 'व्यवहार्यता स्कोर', recommendations: 'शीर्ष 3 सुझाव', recommendation: 'सुझाव', medium: 'मध्यम', mockConsumerBase: 'निजामाबाद ग्रामीण के 10 किमी के भीतर लगभग 8,000 परिवार', mockChannels: ['स्थानीय साप्ताहिक बाजार (संत)', 'सीधे घर पर डिलीवरी', '3 किराना दुकानों के साथ साझेदारी'], mockStrengths: ['स्थानीय डेयरी की मजबूत मांग', 'कम शुरुआती पूंजी की जरूरत'], mockWeaknesses: ['कोल्ड-चेन की सुविधा नहीं', 'पहली बार व्यवसाय संचालन'], mockOpportunities: ['ब्लॉक में जैविक दूध का कोई आपूर्तिकर्ता नहीं', 'पास के शहर की बढ़ती आबादी'], mockThreats: ['गर्मियों में चारे की लागत बढ़ना', 'एक ही दूध खरीदार पर निर्भरता'], mockRisks: ['मई-जून में चारे की कीमत बढ़ना', 'मानसून में परिवहन बाधित होना'], mockNiche: 'स्थानीय शहर के बाजार के लिए पैक किया हुआ दही और छाछ', mockCompetitionReason: '6-8 अनौपचारिक डेयरी विक्रेता, कोई ब्रांडेड नहीं', mockPricingRange: '₹48-55 प्रति लीटर', mockPricingReason: 'खुले दूध से थोड़ा अधिक, स्वच्छता और डिलीवरी से उचित', mockViabilityReason: 'मजबूत मांग, प्रबंधनीय जोखिम और स्पष्ट मूल्य लाभ', mockRecommendations: ['बढ़ाने से पहले मांग जांचने के लिए 4-5 भैंसों से शुरू करें', 'गर्मी से पहले चारा आपूर्तिकर्ता तय करें', 'प्रीमियम के लिए स्वच्छ और घर पहुंच सेवा की पहचान बनाएं'] });
Object.assign(translations.te, { capitalPosition: 'మూలధన స్థితి', contribution: 'మీ సహకారం', financing: 'ఫైనాన్సింగ్', financialShare: 'మీ 10% సహకారం మరియు 90% ఫైనాన్సింగ్ నిర్మాణం.', repaymentProfile: 'చెల్లింపు ప్రొఫైల్', amortizationUnavailable: 'ఈ దరఖాస్తుకు అర్హత లేనందున రుణ చెల్లింపు షెడ్యూల్ అందుబాటులో లేదు.', feasibilityTab: 'సాధ్యత నివేదిక', marketReach: 'మార్కెట్ చేరువ', consumerBase: 'వినియోగదారుల ఆధారం', channels: 'పంపిణీ మార్గాలు', swot: 'SWOT', strengths: 'బలాలు', weaknesses: 'బలహీనతలు', opportunities: 'అవకాశాలు', threats: 'ముప్పులు', localRisks: 'స్థానిక ప్రమాదాలు', opportunity: 'అవకాశం', unservedNiche: 'సేవలు అందని విభాగం', competition: 'పోటీ', competitorDensity: 'పోటీ సాంద్రత', reasoning: 'వివరణ', pricing: 'ధర నిర్ణయ వ్యూహం', recommendedRange: 'సిఫార్సు పరిధి', viability: 'సాధ్యత', viabilityScore: 'సాధ్యత స్కోర్', recommendations: 'ముఖ్యమైన 3 సూచనలు', recommendation: 'సూచన', medium: 'మధ్యస్థం', mockConsumerBase: 'నిజామాబాద్ రూరల్‌కు 10 కి.మీ పరిధిలో సుమారు 8,000 కుటుంబాలు', mockChannels: ['స్థానిక వారపు మార్కెట్ (సంత)', 'నేరుగా ఇంటికి డెలివరీ', '3 కిరాణా దుకాణాలతో భాగస్వామ్యం'], mockStrengths: ['స్థానిక పాలకు బలమైన డిమాండ్', 'ప్రారంభ మూలధనం తక్కువగా అవసరం'], mockWeaknesses: ['కోల్డ్-చెయిన్ సౌకర్యం లేదు', 'మొదటిసారి వ్యాపార నిర్వహణ'], mockOpportunities: ['బ్లాక్‌లో సేంద్రీయ పాల సరఫరాదారు లేరు', 'సమీప పట్టణ జనాభా పెరుగుతోంది'], mockThreats: ['వేసవిలో మేత ఖర్చు పెరుగుతుంది', 'ఒకే పాల కొనుగోలుదారుపై ఆధారపడటం'], mockRisks: ['మే-జూన్‌లో మేత ధరలు పెరగడం', 'వర్షాకాల రవాణా అంతరాయం'], mockNiche: 'స్థానిక పట్టణ మార్కెట్ కోసం ప్యాక్ చేసిన పెరుగు మరియు మజ్జిగ', mockCompetitionReason: '6-8 అనధికార పాల విక్రేతలు, బ్రాండెడ్ విక్రేతలు లేరు', mockPricingRange: 'లీటరుకు ₹48-55', mockPricingReason: 'ప్యాకేజింగ్ మరియు డెలివరీ కారణంగా సాధారణ పాల కంటే కొద్దిగా ఎక్కువ', mockViabilityReason: 'మంచి డిమాండ్, నిర్వహించగల ప్రమాదాలు, స్పష్టమైన ధర ప్రయోజనం', mockRecommendations: ['పెంచే ముందు డిమాండ్‌ను నిర్ధారించడానికి 4-5 గేదెలతో ప్రారంభించండి', 'వేసవికి ముందే మేత సరఫరాదారుని ఖరారు చేయండి', 'పరిశుభ్రత మరియు ఇంటి డెలివరీతో ప్రీమియం బ్రాండ్‌గా నిలవండి'] });
Object.assign(translations.en, { quarterShort: 'Q' });
Object.assign(translations.hi, { quarterShort: 'ति' });
Object.assign(translations.te, { quarterShort: 'త్రై' });
Object.assign(translations.en, { downloadReport: 'Download Full Report (PDF)', generatingReport: 'Generating report...', reportError: 'We could not generate the report. Please try again.', reportTitle: 'Full financial and feasibility report', generatedOn: 'Generated on', financialSummary: 'Financial summary', capitalStructure: 'Capital structure', eligibilityStatus: 'Eligibility status' });
Object.assign(translations.hi, { downloadReport: '\u092a\u0942\u0930\u0940 \u0930\u093f\u092a\u094b\u0930\u094d\u091f \u0921\u093e\u0909\u0928\u0932\u094b\u0921 \u0915\u0930\u0947\u0902 (PDF)', generatingReport: '\u0930\u093f\u092a\u094b\u0930\u094d\u091f \u0924\u0948\u092f\u093e\u0930 \u0915\u0940 \u091c\u093e \u0930\u0939\u0940 \u0939\u0948...', reportError: '\u0930\u093f\u092a\u094b\u0930\u094d\u091f \u0924\u0948\u092f\u093e\u0930 \u0928\u0939\u0940\u0902 \u0939\u094b \u0938\u0915\u0940. \u0915\u0943\u092a\u092f\u093e \u092b\u093f\u0930 \u0915\u094b\u0936\u093f\u0936 \u0915\u0930\u0947\u0902.', reportTitle: '\u092a\u0942\u0930\u0940 \u0935\u093f\u0924\u094d\u0924\u0940\u092f \u0914\u0930 \u0935\u094d\u092f\u093e\u0935\u0939\u093e\u0930\u094d\u092f\u0924\u093e \u0930\u093f\u092a\u094b\u0930\u094d\u091f', generatedOn: '\u0924\u0948\u092f\u093e\u0930 \u0915\u093f\u092f\u093e \u0917\u092f\u093e', financialSummary: '\u0935\u093f\u0924\u094d\u0924\u0940\u092f \u0938\u093e\u0930\u093e\u0902\u0936', capitalStructure: '\u092a\u0942\u0902\u091c\u0940 \u0938\u0902\u0930\u091a\u0928\u093e', eligibilityStatus: '\u092a\u093e\u0924\u094d\u0930\u0924\u093e \u0938\u094d\u0925\u093f\u0924\u093f' });
Object.assign(translations.te, { downloadReport: '\u092a\u0942\u0930\u094d\u0924\u093f \u0928\u093f\u0935\u0947\u0926\u093f\u0915\u0928\u0941 \u0921\u093e\u0909\u0928\u0932\u094b\u0921\u094d \u091a\u0947\u092f\u0902\u0921\u093f (PDF)', generatingReport: '\u0928\u093f\u0935\u0947\u0926\u093f\u0915 \u0930\u0942\u092a\u094a\u0902\u0926\u093f\u0938\u094d\u0924\u094b\u0902\u0926\u093f...', reportError: '\u0928\u093f\u0935\u0947\u0926\u093f\u0915\u0928\u0941 \u0930\u0942\u092a\u093e\u0902\u0926\u093f\u0902\u091a\u0932\u0947\u0915\u092a\u094b\u092f\u093f\u0902\u0926\u093f. \u092e\u0933\u094d\u0932\u0940 \u092a\u094d\u0930\u092f\u0924\u094d\u0928\u093f\u0902\u091a\u0902\u0921\u093f.', reportTitle: '\u092a\u0942\u0930\u094d\u0924\u093f \u0906\u0930\u094d\u0925\u093f\u0915 \u092e\u0930\u093f\u092f\u0941 \u0938\u093e\u0927\u094d\u092f\u0924 \u0928\u093f\u0935\u0947\u0926\u093f\u0915', generatedOn: '\u0930\u0942\u092a\u093e\u0902\u0926\u093f\u0902\u091a\u093f\u0928', financialSummary: '\u0906\u0930\u094d\u0925\u093f\u0915 \u0938\u093e\u0930\u093e\u0902\u0936', capitalStructure: '\u092e\u0942\u0932\u0927\u0928 \u0928\u093f\u0930\u094d\u092e\u093e\u0923\u0902', eligibilityStatus: '\u0905\u0930\u094d\u0939\u0924 \u0938\u094d\u0925\u093f\u0924\u093f' });
Object.assign(translations.te, { downloadReport: '\u0c2a\u0c42\u0c30\u0c4d\u0c24\u0c3f \u0c28\u0c3f\u0c35\u0c47\u0c26\u0c3f\u0c15\u0c28\u0c41 \u0c21\u0c3e\u0c09\u0c28\u0c4d\u200c\u0c32\u0c4b\u0c21\u0c4d \u0c1a\u0c47\u0c2f\u0c02\u0c21\u0c3f (PDF)', generatingReport: '\u0c28\u0c3f\u0c35\u0c47\u0c26\u0c3f\u0c15 \u0c38\u0c3f\u0c26\u0c4d\u0c27\u0c2e\u0c35\u0c41\u0c24\u0c4b\u0c02\u0c26\u0c3f...', reportError: '\u0c28\u0c3f\u0c35\u0c47\u0c26\u0c3f\u0c15\u0c28\u0c41 \u0c38\u0c3f\u0c26\u0c4d\u0c27\u0c02 \u0c1a\u0c47\u0c2f\u0c32\u0c47\u0c15\u0c2a\u0c4b\u0c2f\u0c3f\u0c02\u0c26\u0c3f. \u0c2e\u0c33\u0c4d\u0c32\u0c40 \u0c2a\u0c4d\u0c30\u0c2f\u0c24\u0c4d\u0c28\u0c3f\u0c02\u0c1a\u0c02\u0c21\u0c3f.', reportTitle: '\u0c2a\u0c42\u0c30\u0c4d\u0c24\u0c3f \u0c06\u0c30\u0c4d\u0c25\u0c3f\u0c15 \u0c2e\u0c30\u0c3f\u0c2f\u0c41 \u0c38\u0c3e\u0c27\u0c4d\u0c2f\u0c24 \u0c28\u0c3f\u0c35\u0c47\u0c26\u0c3f\u0c15', generatedOn: '\u0c38\u0c3f\u0c26\u0c4d\u0c27\u0c02 \u0c1a\u0c47\u0c38\u0c3f\u0c28 \u0c24\u0c47\u0c26\u0c3f', financialSummary: '\u0c06\u0c30\u0c4d\u0c25\u0c3f\u0c15 \u0c38\u0c3e\u0c30\u0c3e\u0c02\u0c36\u0c02', capitalStructure: '\u0c2e\u0c42\u0c32\u0c27\u0c28 \u0c28\u0c3f\u0c30\u0c4d\u0c2e\u0c3e\u0c23\u0c02', eligibilityStatus: '\u0c05\u0c30\u0c4d\u0c39\u0c24 \u0c38\u0c4d\u0c25\u0c3f\u0c24\u0c3f' });
Object.assign(translations.en, { requestedFinancing: 'Requested financing' });
Object.assign(translations.hi, { requestedFinancing: '\u092a\u094d\u0930\u0938\u094d\u0924\u093e\u0935\u093f\u0924 \u0935\u093f\u0924\u094d\u0924\u092a\u094b\u0937\u0923' });
Object.assign(translations.te, { requestedFinancing: '\u0c05\u0c21\u0c3f\u0c17\u0c3f\u0c28 \u0c35\u0c3f\u0c24\u0c4d\u0c24\u0c2a\u0c4b\u0c37\u0c23' });
Object.assign(translations.en, { chatTitle: 'Arthniti Assistant', chatSubtitle: 'Understand your business plan and financial assessment with a little more clarity.', chatContextLabel: 'CURRENT CONTEXT', chatNoPlan: 'No onboarding plan yet', chatAssistant: 'Assistant', chatYou: 'You', chatWelcome: 'Hello. I can help you understand your financial plan, feasibility assessment, risks, and next steps.', chatSuggested: 'Suggested questions', chatSuggestionFeasibility: 'Why is my business feasible?', chatSuggestionLoan: 'How much loan can I get?', chatSuggestionRisks: 'What are the biggest risks?', chatSuggestionViability: 'How can I improve my viability score?', chatInputLabel: 'Ask Arthniti Assistant', chatPlaceholder: 'Ask a question about your business or plan...', chatSend: 'Send', chatSending: 'Thinking...', chatError: 'We could not reach the assistant. Please try again.', chatRetry: 'Retry', chatInputHint: 'Enter to send. Shift + Enter for a new line.', feasibilityResponse: 'Your viability score is {score} / 100. {viabilityReason}', loanEligibleResponse: 'Your plan is eligible for the {scheme}. The sanctioned loan is {loan}, at {interest}% for {tenure} years, with an EMI of {emi}.', loanIneligibleResponse: 'This application is not eligible because the project cost exceeds the ₹50 lakh limit. No eligible loan or EMI is being shown.', risksResponse: 'The main risks identified are: {risks}. The threats to watch are: {threats}.', recommendationsResponse: 'Your current viability score is {score} / 100. Recommended next steps: {recommendations}.', generalResponse: 'I can explain your feasibility score, loan eligibility, risks, recommendations, or repayment plan. Try one of the suggested questions.' });
Object.assign(translations.hi, { chatTitle: 'अर्थनीति सहायक', chatSubtitle: 'अपने व्यवसाय की योजना और वित्तीय आकलन को अधिक स्पष्टता से समझें।', chatContextLabel: 'वर्तमान संदर्भ', chatNoPlan: 'अभी कोई ऑनबोर्डिंग योजना नहीं', chatAssistant: 'सहायक', chatYou: 'आप', chatWelcome: 'नमस्ते। मैं आपकी वित्तीय योजना, व्यवहार्यता आकलन, जोखिम और अगले कदम समझने में मदद कर सकता हूं।', chatSuggested: 'सुझाए गए प्रश्न', chatSuggestionFeasibility: 'मेरा व्यवसाय व्यवहार्य क्यों है?', chatSuggestionLoan: 'मुझे कितना ऋण मिल सकता है?', chatSuggestionRisks: 'सबसे बड़े जोखिम क्या हैं?', chatSuggestionViability: 'मैं अपना व्यवहार्यता स्कोर कैसे सुधारूं?', chatInputLabel: 'अर्थनीति सहायक से पूछें', chatPlaceholder: 'अपने व्यवसाय या योजना के बारे में प्रश्न पूछें...', chatSend: 'भेजें', chatSending: 'सोचा जा रहा है...', chatError: 'सहायक से संपर्क नहीं हो सका। कृपया फिर कोशिश करें।', chatRetry: 'फिर कोशिश करें', chatInputHint: 'भेजने के लिए Enter दबाएं। नई पंक्ति के लिए Shift + Enter दबाएं।', feasibilityResponse: 'आपका व्यवहार्यता स्कोर {score} / 100 है। {viabilityReason}', loanEligibleResponse: 'आपकी योजना {scheme} के लिए पात्र है। स्वीकृत ऋण {loan} है, ब्याज {interest}% और अवधि {tenure} वर्ष है। EMI {emi} है।', loanIneligibleResponse: 'यह आवेदन पात्र नहीं है क्योंकि परियोजना लागत ₹50 लाख की सीमा से अधिक है। कोई पात्र ऋण या EMI नहीं दिखाई जा रही है।', risksResponse: 'पहचाने गए मुख्य जोखिम हैं: {risks}। इन खतरों पर ध्यान दें: {threats}।', recommendationsResponse: 'आपका वर्तमान व्यवहार्यता स्कोर {score} / 100 है। सुझाए गए अगले कदम: {recommendations}।', generalResponse: 'मैं आपके व्यवहार्यता स्कोर, ऋण पात्रता, जोखिम, सुझाव या भुगतान योजना को समझा सकता हूं। कोई सुझाया गया प्रश्न चुनें।' });
Object.assign(translations.te, { chatTitle: 'అర్థనితి సహాయకుడు', chatSubtitle: 'మీ వ్యాపార ప్రణాళిక మరియు ఆర్థిక అంచనాను మరింత స్పష్టంగా అర్థం చేసుకోండి.', chatContextLabel: 'ప్రస్తుత సందర్భం', chatNoPlan: 'ఇంకా ఆన్‌బోర్డింగ్ ప్రణాళిక లేదు', chatAssistant: 'సహాయకుడు', chatYou: 'మీరు', chatWelcome: 'నమస్కారం. మీ ఆర్థిక ప్రణాళిక, సాధ్యత అంచనా, ప్రమాదాలు మరియు తదుపరి చర్యలను అర్థం చేసుకోవడంలో నేను సహాయపడతాను.', chatSuggested: 'సూచించిన ప్రశ్నలు', chatSuggestionFeasibility: 'నా వ్యాపారం ఎందుకు సాధ్యమవుతుంది?', chatSuggestionLoan: 'నాకు ఎంత రుణం లభిస్తుంది?', chatSuggestionRisks: 'అతిపెద్ద ప్రమాదాలు ఏమిటి?', chatSuggestionViability: 'నా సాధ్యత స్కోర్‌ను ఎలా మెరుగుపరచాలి?', chatInputLabel: 'అర్థనితి సహాయకుడిని అడగండి', chatPlaceholder: 'మీ వ్యాపారం లేదా ప్రణాళిక గురించి ప్రశ్న అడగండి...', chatSend: 'పంపండి', chatSending: 'ఆలోచిస్తోంది...', chatError: 'సహాయకుడిని చేరుకోలేకపోయాం. దయచేసి మళ్లీ ప్రయత్నించండి.', chatRetry: 'మళ్లీ ప్రయత్నించండి', chatInputHint: 'పంపడానికి Enter నొక్కండి. కొత్త వరుస కోసం Shift + Enter నొక్కండి.', feasibilityResponse: 'మీ సాధ్యత స్కోర్ {score} / 100. {viabilityReason}', loanEligibleResponse: 'మీ ప్రణాళిక {scheme}కు అర్హత కలిగి ఉంది. మంజూరైన రుణం {loan}, వడ్డీ {interest}%, కాలవ్యవధి {tenure} సంవత్సరాలు, EMI {emi}.', loanIneligibleResponse: 'ప్రాజెక్టు ఖర్చు ₹50 లక్షల పరిమితిని మించినందున ఈ దరఖాస్తుకు అర్హత లేదు. అర్హత ఉన్న రుణం లేదా EMI చూపించబడదు.', risksResponse: 'గుర్తించిన ప్రధాన ప్రమాదాలు: {risks}. గమనించాల్సిన ముప్పులు: {threats}.', recommendationsResponse: 'మీ ప్రస్తుత సాధ్యత స్కోర్ {score} / 100. సూచించిన తదుపరి చర్యలు: {recommendations}.', generalResponse: 'మీ సాధ్యత స్కోర్, రుణ అర్హత, ప్రమాదాలు, సూచనలు లేదా చెల్లింపు ప్రణాళికను నేను వివరించగలను. సూచించిన ప్రశ్నను ఎంచుకోండి.' });
Object.assign(translations.en, { chatEyebrow: 'ARTHNITI / ASSISTANT' });
Object.assign(translations.hi, { chatEyebrow: 'अर्थनीति / सहायक' });
Object.assign(translations.te, { chatEyebrow: 'అర్థనితి / సహాయకుడు' });
Object.assign(translations.en, { askArthniti: 'Ask Arthniti', chatClose: 'Close' });
Object.assign(translations.hi, { askArthniti: 'अर्थनीति से पूछें', chatClose: 'बंद करें' });
Object.assign(translations.te, { askArthniti: 'అర్థనితిని అడగండి', chatClose: 'మూసివేయండి' });
Object.assign(translations.en, { newAssessment: 'New assessment' });
Object.assign(translations.hi, { newAssessment: 'नया आकलन' });
Object.assign(translations.te, { newAssessment: 'కొత్త అంచనా' });
Object.assign(translations.en, { history: 'History', recentAssessments: 'Recent Assessments', assessmentsEyebrow: 'ARTHNITI / HISTORY', assessmentsSubtitle: 'Review previous plans or begin a new assessment.', viewAssessment: 'View assessment', startFirstAssessment: 'Start your first assessment', noAssessments: 'No assessments yet', created: 'Created' });
Object.assign(translations.hi, { history: 'इतिहास', recentAssessments: 'हाल के आकलन', assessmentsEyebrow: 'ARTHNITI / इतिहास', assessmentsSubtitle: 'पिछली योजनाएं देखें या नया आकलन शुरू करें।', viewAssessment: 'आकलन देखें', startFirstAssessment: 'अपना पहला आकलन शुरू करें', noAssessments: 'अभी कोई आकलन नहीं', created: 'बनाया गया' });
Object.assign(translations.te, { history: 'చరిత్ర', recentAssessments: 'ఇటీవలి అంచనాలు', assessmentsEyebrow: 'ARTHNITI / చరిత్ర', assessmentsSubtitle: 'మునుపటి ప్రణాళికలను చూడండి లేదా కొత్త అంచనాను ప్రారంభించండి.', viewAssessment: 'అంచనాను చూడండి', startFirstAssessment: 'మీ మొదటి అంచనాను ప్రారంభించండి', noAssessments: 'ఇంకా అంచనాలు లేవు', created: 'సృష్టించిన తేదీ' });
Object.assign(translations.en, { repaymentSummary: 'Repayment summary', totalInterest: 'Total interest', totalRepayment: 'Total repayment', repaymentInsightOne: 'Your monthly repayment remains fixed while the share going toward principal increases over time.', repaymentInsightTwo: 'Interest is highest at the beginning as it is calculated on the outstanding balance.', repaymentInsightThree: 'The balance reduces steadily across the repayment period.' });
Object.assign(translations.hi, { repaymentSummary: 'भुगतान सारांश', totalInterest: 'कुल ब्याज', totalRepayment: 'कुल भुगतान', repaymentInsightOne: 'आपका मासिक भुगतान स्थिर रहता है, जबकि समय के साथ मूलधन का हिस्सा बढ़ता जाता है।', repaymentInsightTwo: 'शुरुआत में ब्याज अधिक होता है क्योंकि इसकी गणना बकाया राशि पर की जाती है।', repaymentInsightThree: 'भुगतान अवधि के दौरान बकाया राशि लगातार कम होती जाती है।' });
Object.assign(translations.te, { repaymentSummary: 'చెల్లింపు సారాంశం', totalInterest: 'మొత్తం వడ్డీ', totalRepayment: 'మొత్తం చెల్లింపు', repaymentInsightOne: 'మీ నెలవారీ చెల్లింపు స్థిరంగా ఉంటుంది, అయితే కాలక్రమేణా అసలు మొత్తానికి వెళ్తున్న భాగం పెరుగుతుంది.', repaymentInsightTwo: 'బకాయి మొత్తంపై వడ్డీ లెక్కించబడుతుంది కాబట్టి ప్రారంభంలో వడ్డీ ఎక్కువగా ఉంటుంది.', repaymentInsightThree: 'చెల్లింపు కాలంలో బకాయి మొత్తం క్రమంగా తగ్గుతుంది.' });
Object.assign(translations.en, { genericConsumerBase: 'Local demand should be assessed across nearby households and town markets.', mockChannelsGeneric: ['Local weekly market', 'Direct customer delivery', 'Nearby retail partnerships'], genericStrengths: ['Clear local customer need can support a focused start', 'Small-scale operations allow practical testing'], genericWeaknesses: ['First-time operators may need guidance', 'Supply and transport reliability require planning'], genericOpportunities: ['Nearby markets may offer room for a focused local offering', 'A consistent service can build repeat customers'], genericThreats: ['Input costs may change with the season', 'Dependence on a small number of buyers or suppliers'], genericRisks: ['Input price changes can affect margins', 'Weather or transport disruption can affect delivery'], genericNiche: 'A focused offering for customers in the selected local market', genericCompetition: 'Local competition should be mapped before investment and expansion.', genericPricingRange: 'Set after local cost and competitor checks', genericPricingReason: 'Pricing should cover costs while remaining appropriate for the selected market.', genericViabilityReason: 'The assessment provides a practical starting point; validate demand and operating costs locally.', genericRecommendations: ['Validate demand with local customers before scaling', 'Plan reliable suppliers and delivery routes', 'Record costs and sales from the first operating month'] });
Object.assign(translations.hi, { genericConsumerBase: 'स्थानीय मांग का आकलन आसपास के परिवारों और शहर के बाजारों में किया जाना चाहिए।', mockChannelsGeneric: ['स्थानीय साप्ताहिक बाजार', 'सीधे ग्राहक तक डिलीवरी', 'नजदीकी खुदरा साझेदारियां'], genericStrengths: ['स्थानीय ग्राहकों की स्पष्ट जरूरत केंद्रित शुरुआत में मदद कर सकती है', 'छोटे स्तर पर संचालन से व्यावहारिक परीक्षण संभव है'], genericWeaknesses: ['पहली बार काम करने वाले संचालकों को मार्गदर्शन की जरूरत हो सकती है', 'आपूर्ति और परिवहन की विश्वसनीयता के लिए योजना जरूरी है'], genericOpportunities: ['नजदीकी बाजार केंद्रित स्थानीय पेशकश के लिए अवसर दे सकते हैं', 'नियमित सेवा से दोबारा आने वाले ग्राहक बन सकते हैं'], genericThreats: ['मौसम के साथ लागत बदल सकती है', 'कम खरीदारों या आपूर्तिकर्ताओं पर निर्भरता जोखिम बढ़ा सकती है'], genericRisks: ['इनपुट की कीमत बदलने से मार्जिन प्रभावित हो सकता है', 'मौसम या परिवहन में बाधा डिलीवरी को प्रभावित कर सकती है'], genericNiche: 'चयनित स्थानीय बाजार के ग्राहकों के लिए केंद्रित पेशकश', genericCompetition: 'निवेश और विस्तार से पहले स्थानीय प्रतिस्पर्धा का आकलन करें।', genericPricingRange: 'स्थानीय लागत और प्रतिस्पर्धा की जांच के बाद तय करें', genericPricingReason: 'मूल्य निर्धारण में लागत शामिल होनी चाहिए और चुने हुए बाजार के लिए उपयुक्त रहना चाहिए।', genericViabilityReason: 'यह आकलन व्यावहारिक शुरुआत देता है; स्थानीय मांग और संचालन लागत की पुष्टि करें।', genericRecommendations: ['विस्तार से पहले स्थानीय ग्राहकों से मांग की पुष्टि करें', 'विश्वसनीय आपूर्तिकर्ताओं और डिलीवरी मार्गों की योजना बनाएं', 'पहले महीने से लागत और बिक्री का रिकॉर्ड रखें'] });
Object.assign(translations.te, { genericConsumerBase: 'సమీపంలోని కుటుంబాలు మరియు పట్టణ మార్కెట్లలో స్థానిక డిమాండ్‌ను అంచనా వేయాలి.', mockChannelsGeneric: ['స్థానిక వారపు మార్కెట్', 'నేరుగా వినియోగదారులకు డెలివరీ', 'సమీప రిటైల్ భాగస్వామ్యాలు'], genericStrengths: ['స్థానిక వినియోగదారుల స్పష్టమైన అవసరం కేంద్రీకృత ప్రారంభానికి తోడ్పడుతుంది', 'చిన్న స్థాయి నిర్వహణతో ఆచరణాత్మక పరీక్ష సాధ్యమవుతుంది'], genericWeaknesses: ['మొదటిసారి నిర్వహించే వారికి మార్గదర్శకత్వం అవసరం కావచ్చు', 'సరఫరా మరియు రవాణా విశ్వసనీయతకు ప్రణాళిక అవసరం'], genericOpportunities: ['సమీప మార్కెట్లు కేంద్రీకృత స్థానిక అవకాశాన్ని అందించవచ్చు', 'స్థిరమైన సేవ తిరిగి వచ్చే వినియోగదారులను పెంచుతుంది'], genericThreats: ['కాలానుగుణంగా ఇన్‌పుట్ ఖర్చులు మారవచ్చు', 'కొద్దిమంది కొనుగోలుదారులు లేదా సరఫరాదారులపై ఆధారపడటం ప్రమాదకరం'], genericRisks: ['ఇన్‌పుట్ ధరల మార్పు మార్జిన్లను ప్రభావితం చేయవచ్చు', 'వాతావరణం లేదా రవాణా అంతరాయం డెలివరీని ప్రభావితం చేయవచ్చు'], genericNiche: 'ఎంచుకున్న స్థానిక మార్కెట్ వినియోగదారుల కోసం కేంద్రీకృత ఆఫర్', genericCompetition: 'పెట్టుబడి మరియు విస్తరణకు ముందు స్థానిక పోటీని పరిశీలించాలి.', genericPricingRange: 'స్థానిక ఖర్చులు మరియు పోటీ పరిశీలన తర్వాత నిర్ణయించాలి', genericPricingReason: 'ధరలో ఖర్చులు ఉండాలి మరియు ఎంచుకున్న మార్కెట్‌కు తగినదిగా ఉండాలి.', genericViabilityReason: 'ఈ అంచనా ఆచరణాత్మక ప్రారంభాన్ని అందిస్తుంది; స్థానిక డిమాండ్ మరియు నిర్వహణ ఖర్చులను నిర్ధారించండి.', genericRecommendations: ['విస్తరించే ముందు స్థానిక వినియోగదారులతో డిమాండ్‌ను నిర్ధారించండి', 'విశ్వసనీయ సరఫరాదారులు మరియు డెలివరీ మార్గాలను ప్లాన్ చేయండి', 'మొదటి నెల నుంచే ఖర్చులు మరియు అమ్మకాల రికార్డులు ఉంచండి'] });
Object.assign(translations.en, { dairyConsumerBase: 'Existing dairy demand should be validated across nearby households and town markets in {location}.' });
Object.assign(translations.hi, { dairyConsumerBase: '{location} में आसपास के परिवारों और शहर के बाजारों में डेयरी की मांग की पुष्टि की जानी चाहिए।' });
Object.assign(translations.te, { dairyConsumerBase: '{location}లో సమీప కుటుంబాలు మరియు పట్టణ మార్కెట్లలో డెయిరీ డిమాండ్‌ను నిర్ధారించాలి.' });
Object.assign(translations.en, { bankLanguage: 'Language', bankEyebrow: 'ARTHNITI / SCA', bankTitle: 'State Channelizing Agency View', bankSubtitle: 'Transparent Fund Disbursement', bankLedgerLabel: 'Ledger entries', bankLedgerEyebrow: 'DISBURSEMENT LEDGER', bankLedgerTitle: 'Fund movement', mockData: 'MOCK DATA', applicationId: 'Application ID', beneficiary: 'Beneficiary', sanctionedAmount: 'Sanctioned amount', disbursed: 'Disbursed (tx hash)', repaymentsLogged: 'Repayments logged', status: 'Status', action: 'Action', pending: 'Pending', disbursedStatus: 'Disbursed', repaid: 'Repaid', recordDisbursement: 'Record disbursement', disbursing: 'Recording...', recorded: 'Recorded', noTransaction: 'No on-chain transaction', bankLoading: 'Loading ledger...', bankError: 'The ledger could not be loaded. Please try again.', disbursementError: 'The disbursement could not be recorded. Please try again.', mockDisbursementNotice: 'Mock disbursement recorded. No blockchain transaction was created.' });
Object.assign(translations.hi, { bankLanguage: 'भाषा', bankEyebrow: 'अर्थनीति / एससीए', bankTitle: 'राज्य चैनलाइजिंग एजेंसी दृश्य', bankSubtitle: 'पारदर्शी निधि वितरण', bankLedgerLabel: 'लेजर प्रविष्टियां', bankLedgerEyebrow: 'वितरण लेजर', bankLedgerTitle: 'निधि प्रवाह', mockData: 'डेमो डेटा', applicationId: 'आवेदन आईडी', beneficiary: 'लाभार्थी', sanctionedAmount: 'स्वीकृत राशि', disbursed: 'वितरित (लेनदेन हैश)', repaymentsLogged: 'दर्ज भुगतान', status: 'स्थिति', action: 'कार्रवाई', pending: 'लंबित', disbursedStatus: 'वितरित', repaid: 'चुकाया गया', recordDisbursement: 'वितरण दर्ज करें', disbursing: 'दर्ज हो रहा है...', recorded: 'दर्ज', noTransaction: 'कोई ऑन-चेन लेनदेन नहीं', bankLoading: 'लेजर लोड हो रहा है...', bankError: 'लेजर लोड नहीं हो सका। कृपया फिर कोशिश करें।', disbursementError: 'वितरण दर्ज नहीं हो सका। कृपया फिर कोशिश करें।', mockDisbursementNotice: 'डेमो वितरण दर्ज किया गया। कोई ब्लॉकचेन लेनदेन नहीं बनाया गया।' });
Object.assign(translations.te, { bankLanguage: 'భాష', bankEyebrow: 'అర్థనితి / SCA', bankTitle: 'రాష్ట్ర ఛానలైజింగ్ ఏజెన్సీ వీక్షణ', bankSubtitle: 'పారదర్శక నిధుల పంపిణీ', bankLedgerLabel: 'లెడ్జర్ ఎంట్రీలు', bankLedgerEyebrow: 'పంపిణీ లెడ్జర్', bankLedgerTitle: 'నిధుల కదలిక', mockData: 'మాక్ డేటా', applicationId: 'దరఖాస్తు ID', beneficiary: 'లబ్ధిదారు', sanctionedAmount: 'మంజూరైన మొత్తం', disbursed: 'పంపిణీ (లావాదేవీ హాష్)', repaymentsLogged: 'నమోదైన చెల్లింపులు', status: 'స్థితి', action: 'చర్య', pending: 'పెండింగ్', disbursedStatus: 'పంపిణీ అయింది', repaid: 'తీర్చబడింది', recordDisbursement: 'పంపిణీ నమోదు చేయండి', disbursing: 'నమోదవుతోంది...', recorded: 'నమోదైంది', noTransaction: 'ఆన్-చెయిన్ లావాదేవీ లేదు', bankLoading: 'లెడ్జర్ లోడ్ అవుతోంది...', bankError: 'లెడ్జర్ లోడ్ కాలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.', disbursementError: 'పంపిణీ నమోదు కాలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.', mockDisbursementNotice: 'మాక్ పంపిణీ నమోదు అయింది. బ్లాక్‌చెయిన్ లావాదేవీ సృష్టించలేదు.' });
Object.assign(translations.en, { assessmentDate: 'Assessment date' });
Object.assign(translations.hi, { assessmentDate: 'आकलन की तारीख' });
Object.assign(translations.te, { assessmentDate: 'అంచనా తేదీ' });
